import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { extendedTranslations, getExtendedTranslation } from '@/lib/translations';

export type SupportedLanguage = 'en' | 'hi' | 'ta' | 'te' | 'pa' | 'ur' | 'ml';

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  const setLanguage = (newLanguage: SupportedLanguage) => {
    setLanguageState(newLanguage);
    localStorage.setItem('selectedLanguage', newLanguage);
  };

  useEffect(() => {
    const storedLanguage = localStorage.getItem('selectedLanguage') as SupportedLanguage;
    const farmerData = localStorage.getItem('farmerData');
    
    if (storedLanguage) {
      setLanguageState(storedLanguage);
    } else if (farmerData) {
      const parsed = JSON.parse(farmerData);
      if (parsed.language) {
        setLanguageState(parsed.language as SupportedLanguage);
      }
    }
  }, []);

  const t = (key: string): string => {
    // First try the main translations
    const mainTranslation = translations[language]?.[key];
    if (mainTranslation) {
      return mainTranslation;
    }
    
    // Then try extended translations
    const extendedTranslation = getExtendedTranslation(language, key);
    if (extendedTranslation !== key) {
      return extendedTranslation;
    }
    
    // Fallback to English
    return translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'Welcome to Krishi Dost',
    'smartCropAdvisory': 'Smart Crop Advisory',
    'krishiDost': 'Krishi Dost',
    'digitalFarmingCompanion': 'Your Digital Farming Companion',
    'getStarted': 'Get Started',
    'tutorialVideo': 'Tutorial Video',
    'skip': 'Skip',
    'chooseYourLanguage': 'Choose Your Language',
    
    // Form Fields
    'yourName': 'Your Name',
    'enterFullName': 'Enter your full name',
    'password': 'Password',
    'enterPassword': 'Enter your password',
    'confirmPassword': 'Confirm Password',
    'confirmYourPassword': 'Confirm your password',
    'login': 'Login',
    'register': 'Register',
    'continueOffline': 'Continue Offline',
    
    // Navigation & Pages
    'dashboard': 'Dashboard',
    'myCrop': 'My Crop',
    'myCrops': 'My Crops',
    'aiCropCalendar': 'AI Crop Calendar',
    'marketPrice': 'Market Price',
    'marketPrices': 'Market Prices',
    'govtSchemes': 'Govt Schemes',
    'expertHelp': 'Expert Help',
    'cameraDetection': 'Camera Detection',
    'location': 'Location',
    'mainMenu': 'Main Menu',
    'manageLocation': 'Manage your location',
    
    // Dashboard
    'goodMorningFarmer': 'Good Morning, Farmer!',
    'farmingDashboardToday': 'Here\'s your farming dashboard for today',
    'checkCropsField': 'Check your crops in the field',
    'todayMandiRates': 'Today\'s mandi rates',
    'availableGovtSchemes': 'Available government schemes',
    'connectExperts': 'Connect with farming experts',
    'weather': 'Weather',
    'rainfall': 'Rainfall',
    'season': 'Season',
    'alerts': 'Alerts',
    'newAlerts': 'new alerts',
    'voiceAssistant': 'Voice Assistant',
    'askFarmingQuestions': 'Ask me any farming questions',
    'startVoiceChat': 'Start Voice Chat',
    'open': 'Open',
    'recentActivity': 'Recent Activity',
    'riceCropUpdated': 'Rice crop status updated',
    'hoursAgo': 'hours ago',
    'marketPriceAlert': 'Market price alert received',
    
    // Login & Auth
    'loginToKrishiDost': 'Login to Krishi Dost',
    'usernameLabel': 'Username (Farmer Name)',
    'enterName': 'Enter your name',
    'state': 'State',
    'selectState': 'Select State',
    'district': 'District',
    'selectDistrict': 'Select District',
    'village': 'Village',
    'selectVillage': 'Select Village',
    
    // Crop Management
    'addNewCrop': 'Add New Crop',
    'addCrop': 'Add Crop',
    'cropName': 'Crop Name',
    'variety': 'Variety',
    'plantedDate': 'Planted Date',
    'expectedHarvest': 'Expected Harvest',
    'autoCalculated': 'Auto calculated',
    'harvestDateAutoCalculated': 'Harvest date is auto-calculated based on crop type',
    'area': 'Area',
    'status': 'Status',
    'growing': 'Growing',
    'flowering': 'Flowering',
    'harvesting': 'Harvesting',
    'harvested': 'Harvested',
    'selectCategory': 'Select category',
    'edit': 'Edit',
    'delete': 'Delete',
    'manageCrops': 'Manage your crops and track their progress',
    'todayTipsReminders': 'Today\'s Tips & Reminders',
    'irrigationReminder': 'Irrigation Reminder',
    'waterRiceCrop': 'Water your rice crop - ideal time between 6-8 AM',
    'pestAlert': 'Pest Alert',
    'brownPlanthopper': 'Brown Planthopper spotted in nearby fields',
    'fertilizerSchedule': 'Fertilizer Schedule',
    'applyUreaFertilizer': 'Apply Urea fertilizer to wheat crop today',
    
    // Market
    'latestMandiRates': 'Latest mandi rates and commodity prices',
    'searchCropsVarieties': 'Search crops and varieties...',
    'allCrops': 'All Crops',
    'cereals': 'Cereals',
    'cashCrops': 'Cash Crops',
    'priceAlerts': 'Price Alerts',
    
    // Government & Schemes
    'governmentSchemes': 'Government Schemes',
    'exploreApplySchemes': 'Explore and apply for various government schemes',
    'governmentProcurement': 'Government Procurement',
    'mspWheatAnnounced': 'MSP for wheat announced at ₹2325/quintal',
    'weatherClimate': 'Weather & Climate',
    
    // Common
    'submit': 'Submit',
    'cancel': 'Cancel',
    'save': 'Save',
    'back': 'Back',
    'next': 'Next',
    'welcome': 'Welcome',
    'loading': 'Loading...',
    'newToKrishiDost': 'New to Krishi Dost?',
    'createNewAccount': 'Create New Account',
  },
  hi: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'कृषि दोस्त में आपका स्वागत है',
    'smartCropAdvisory': 'स्मार्ट फसल सलाहकार',
    'krishiDost': 'कृषि दोस्त',
    'digitalFarmingCompanion': 'आपका डिजिटल कृषि साथी',
    'getStarted': 'शुरू करें',
    'tutorialVideo': 'ट्यूटोरियल वीडियो',
    'skip': 'छोड़ें',
    'chooseYourLanguage': 'अपनी भाषा चुनें',
    
    // Form Fields
    'yourName': 'आपका नाम',
    'enterFullName': 'अपना पूरा नाम दर्ज करें',
    'password': 'पासवर्ड',
    'enterPassword': 'अपना पासवर्ड दर्ज करें',
    'confirmPassword': 'पासवर्ड की पुष्टि करें',
    'confirmYourPassword': 'अपने पासवर्ड की पुष्टि करें',
    'login': 'लॉगिन',
    'register': 'पंजीकरण',
    'continueOffline': 'ऑफलाइन जारी रखें',
    
    // Navigation & Pages
    'dashboard': 'डैशबोर्ड',
    'myCrop': 'मेरी फसल',
    'myCrops': 'मेरी फसलें',
    'aiCropCalendar': 'AI फसल कैलेंडर',
    'marketPrice': 'बाजार भाव',
    'marketPrices': 'बाजार भाव',
    'govtSchemes': 'सरकारी योजनाएं',
    'expertHelp': 'विशेषज्ञ सहायता',
    'cameraDetection': 'कैमरा जांच',
    'location': 'स्थान',
    'mainMenu': 'मुख्य मेनू',
    'manageLocation': 'अपना स्थान प्रबंधित करें',
    
    // Dashboard
    'goodMorningFarmer': 'सुप्रभात, किसान भाई!',
    'farmingDashboardToday': 'आज के लिए आपका कृषि डैशबोर्ड',
    'checkCropsField': 'खेत में अपनी फसलों की जांच करें',
    'todayMandiRates': 'आज के मंडी भाव',
    'availableGovtSchemes': 'उपलब्ध सरकारी योजनाएं',
    'connectExperts': 'कृषि विशेषज्ञों से जुड़ें',
    'weather': 'मौसम',
    'rainfall': 'वर्षा',
    'season': 'मौसम',
    'alerts': 'अलर्ट',
    'newAlerts': 'नए अलर्ट',
    'voiceAssistant': 'आवाज सहायक',
    'askFarmingQuestions': 'मुझसे कोई भी कृषि प्रश्न पूछें',
    'startVoiceChat': 'आवाज चैट शुरू करें',
    'open': 'खोलें',
    'recentActivity': 'हाल की गतिविधि',
    'riceCropUpdated': 'धान की फसल की स्थिति अपडेट की गई',
    'hoursAgo': 'घंटे पहले',
    'marketPriceAlert': 'बाजार भाव अलर्ट प्राप्त हुआ',
    
    // Login & Auth
    'loginToKrishiDost': 'कृषि दोस्त में लॉगिन करें',
    'usernameLabel': 'उपयोगकर्ता नाम (किसान का नाम)',
    'enterName': 'अपना नाम दर्ज करें',
    'state': 'राज्य',
    'selectState': 'राज्य चुनें',
    'district': 'जिला',
    'selectDistrict': 'जिला चुनें',
    'village': 'गांव',
    'selectVillage': 'गांव चुनें',
    
    // Crop Management
    'addNewCrop': 'नई फसल जोड़ें',
    'addCrop': 'फसल जोड़ें',
    'cropName': 'फसल का नाम',
    'variety': 'किस्म',
    'plantedDate': 'बुवाई की तारीख',
    'expectedHarvest': 'अपेक्षित कटाई',
    'autoCalculated': 'स्वत: गणना',
    'harvestDateAutoCalculated': 'कटाई की तारीख फसल के प्रकार के आधार पर स्वत: गणना की गई है',
    'area': 'क्षेत्रफल',
    'status': 'स्थिति',
    'growing': 'बढ़ रही है',
    'flowering': 'फूल आना',
    'harvesting': 'कटाई',
    'harvested': 'कटाई हो गई',
    'selectCategory': 'श्रेणी चुनें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'manageCrops': 'अपनी फसलों का प्रबंधन करें और उनकी प्रगति को ट्रैक करें',
    'todayTipsReminders': 'आज के सुझाव और अनुस्मारक',
    'irrigationReminder': 'सिंचाई की याद',
    'waterRiceCrop': 'अपनी धान की फसल को पानी दें - सुबह 6-8 बजे के बीच आदर्श समय',
    'pestAlert': 'कीट चेतावनी',
    'brownPlanthopper': 'आसपास के खेतों में भूरा फुदका देखा गया',
    'fertilizerSchedule': 'उर्वरक अनुसूची',
    'applyUreaFertilizer': 'आज गेहूं की फसल में यूरिया उर्वरक डालें',
    
    // Market
    'latestMandiRates': 'नवीनतम मंडी दरें और कमोडिटी मूल्य',
    'searchCropsVarieties': 'फसलों और किस्मों की खोज करें...',
    'allCrops': 'सभी फसलें',
    'cereals': 'अनाज',
    'cashCrops': 'नकदी फसलें',
    'priceAlerts': 'मूल्य चेतावनी',
    
    // Government & Schemes
    'governmentSchemes': 'सरकारी योजनाएं',
    'exploreApplySchemes': 'विभिन्न सरकारी योजनाओं का अन्वेषण और आवेदन करें',
    'governmentProcurement': 'सरकारी खरीद',
    'mspWheatAnnounced': 'गेहूं के लिए MSP ₹2325/क्विंटल की घोषणा',
    'weatherClimate': 'मौसम और जलवायु',
    
    // Common
    'submit': 'जमा करें',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'back': 'वापस',
    'next': 'आगे',
    'welcome': 'स्वागत',
    'loading': 'लोड हो रहा है...',
    'newToKrishiDost': 'कृषि दोस्त में नए हैं?',
    'createNewAccount': 'नया खाता बनाएं',
    
    // Crop/Commodity translations
    'Rice': 'चावल',
    'Wheat': 'गेहूँ', 
    'Maize': 'मक्का',
    'Cotton': 'कपास',
    'Sugarcane': 'गन्ना',
    'Soybean': 'सोयाबीन',
    'Basmati': 'बासमती',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032', 
    'Kapas': 'कपास',
    'Yellow Corn': 'पीली मक्का',
    'JS-335': 'JS-335',
    
    // Scheme name translations
    'PM-KISAN': 'प्रधानमंत्री किसान सम्मान निधि',
    'Crop Insurance': 'फसल बीमा',
    'Soil Health Card': 'मिट्टी स्वास्थ्य कार्ड',
    'KCC': 'किसान क्रेडिट कार्ड',
    'Organic Farming': 'जैविक खेती',
    'Solar Pump': 'सौर पंप',
    
    // Additional missing translations
    'viewDetails': 'विवरण देखें',
    'marketTips': 'बाजार सुझाव',
    'bestSellingTime': 'सबसे अच्छा बिक्री समय',
    'riceExpectedRise': 'चावल की कीमत बढ़ने की उम्मीद',
    'searchSchemes': 'योजनाओं को खोजें...',
    'all': 'सभी',
    'central': 'केंद्रीय',
    'totalSchemes': 'कुल योजनाएं',
    'avgBenefit': 'औसत लाभ',
    'beneficiaries': 'लाभार्थी',
    'ongoing': 'चल रही',
    'requiredDocuments': 'आवश्यक दस्तावेज',
    'applyNow': 'अभी आवेदन करें',
    'applicationTips': 'आवेदन सुझाव',
    'documentsReady': 'सभी दस्तावेज तैयार रखें',
    'applyEarly': 'अंतिम तिथि से पहले आवेदन करें',
    'visitCSC': 'नजदीकी CSC या कृषि कार्यालय जाकर सहायता लें',
    'keepReceipts': 'सभी रसीदों को सुरक्षित रखें',
    'dashboardOverview': 'डैशबोर्ड अवलोकन',
    'manageYourCrops': 'अपनी फसलों का प्रबंधन करें',
    'smartFarmingCalendar': 'स्मार्ट खेती कैलेंडर',
    'getCurrentMarketRates': 'वर्तमान बाजार दरें',
    'getExpertAdvice': 'विशेषज्ञ सलाह प्राप्त करें',
    'identifyCropDiseases': 'फसल रोगों की पहचान करें',
    
    // Additional missing translations
    'rice': 'चावल',
    'wheat': 'गेहूँ',
    'corn': 'मक्का',
    'maize': 'मक्का',
    'millets': 'बाजरा',
    'oats': 'जई',
    'soybeans': 'सोयाबीन',
    'soybean': 'सोयाबीन',
    'sugarcane': 'गन्ना',
    'cotton': 'कपास',
    'chickpea': 'चना',
    'mustard': 'सरसों',
    'potato': 'आलू',
    'tomato': 'टमाटर',
    'onion': 'प्याज',
    'other': 'अन्य',
    'Rice': 'चावल',
    'Wheat': 'गेहूँ',
    'Maize': 'मक्का',
    'Cotton': 'कपास',
    'Sugarcane': 'गन्ना',
    'Soybean': 'सोयाबीन',
    'Basmati': 'बासमती',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032',
    'Kapas': 'कपास',
    'Yellow Corn': 'पीली मक्का',
    'JS-335': 'JS-335'
  },
  ta: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'கிருஷி தோஸ்ட்டுக்கு வரவேற்கிறோம்',
    'smartCropAdvisory': 'ஸ்மார்ட் பயிர் ஆலோசனை',
    'krishiDost': 'கிருஷி தோஸ்ட்',
    'digitalFarmingCompanion': 'உங்கள் டிஜிட்டல் விவசாய துணை',
    'getStarted': 'தொடங்குங்கள்',
    'tutorialVideo': 'டுடோரியல் வீடியோ',
    'skip': 'தவிர்க்கவும்',
    'chooseYourLanguage': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    
    // Form Fields
    'yourName': 'உங்கள் பெயர்',
    'enterFullName': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'password': 'கடவுச்சொல்',
    'enterPassword': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'confirmYourPassword': 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'login': 'உள்நுழைய',
    'register': 'பதிவு',
    'continueOffline': 'ஆஃப்லைனில் தொடரவும்',
    
    // Navigation & Pages
    'dashboard': 'டாஷ்போர்டு',
    'myCrop': 'என் பயிர்',
    'myCrops': 'என் பயிர்கள்',
    'aiCropCalendar': 'AI பயிர் நாட்காட்டி',
    'marketPrice': 'சந்தை விலை',
    'marketPrices': 'சந்தை விலைகள்',
    'govtSchemes': 'அரசு திட்டங்கள்',
    'expertHelp': 'நிபுணர் உதவி',
    'cameraDetection': 'கேமரா கண்டறிதல்',
    'mainMenu': 'முதன்மை மெனு',
    
    // Dashboard
    'goodMorningFarmer': 'காலை வணக்கம், விவசாயி!',
    'farmingDashboardToday': 'இன்றைய உங்கள் விவசாய டாஷ்போர்டு இங்கே',
    'checkCropsField': 'வயலில் உங்கள் பயிர்களைச் சரிபார்க்கவும்',
    'todayMandiRates': 'இன்றைய மண்டி விலைகள்',
    'availableGovtSchemes': 'கிடைக்கும் அரசு திட்டங்கள்',
    'connectExperts': 'விவசாய நிபுணர்களுடன் இணைக்கவும்',
    'weather': 'வானிலை',
    'rainfall': 'மழைப்பொழிவு',
    'season': 'பருவம்',
    'alerts': 'எச்சரிக்கைகள்',
    'newAlerts': 'புதிய எச்சரிக்கைகள்',
    'voiceAssistant': 'குரல் உதவியாளர்',
    'askFarmingQuestions': 'எந்த விவசாய கேள்விகளையும் என்னிடம் கேளுங்கள்',
    'startVoiceChat': 'குரல் அரட்டையைத் தொடங்கவும்',
    'open': 'திறக்கவும்',
    'recentActivity': 'சமீபத்திய செயல்பாடு',
    'riceCropUpdated': 'நெல் பயிர் நிலை புதுப்பிக்கப்பட்டது',
    'hoursAgo': 'மணி நேரங்களுக்கு முன்பு',
    'marketPriceAlert': 'சந்தை விலை எச்சரிக்கை பெறப்பட்டது',
    
    // Login & Auth
    'loginToKrishiDost': 'கிருஷி தோஸ்ட்டில் உள்நுழையவும்',
    'usernameLabel': 'பயனர்பெயர் (விவசாயி பெயர்)',
    'enterName': 'உங்கள் பெயரை உள்ளிடவும்',
    'state': 'மாநிலம்',
    'selectState': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    'district': 'மாவட்டம்',
    'selectDistrict': 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    'village': 'கிராமம்',
    'selectVillage': 'கிராமத்தைத் தேர்ந்தெடுக்கவும்',
    
    // Crop Management
    'addNewCrop': 'புதிய பயிர் சேர்க்கவும்',
    'addCrop': 'பயிர் சேர்க்கவும்',
    'cropName': 'பயிர் பெயர்',
    'variety': 'வகை',
    'plantedDate': 'நடப்பட்ட தேதி',
    'expectedHarvest': 'எதிர்பார்க்கப்படும் அறுவடை',
    'autoCalculated': 'தானாக கணக்கிடப்பட்டது',
    'harvestDateAutoCalculated': 'அறுவடை தேதி பயிர் வகையின் அடிப்படையில் தானாக கணக்கிடப்படுகிறது',
    'area': 'பரப்பளவு',
    'status': 'நிலை',
    'growing': 'வளர்ந்து கொண்டிருக்கிறது',
    'flowering': 'பூக்கும் நிலை',
    'harvesting': 'அறுவடை',
    'harvested': 'அறுவடை செய்யப்பட்டது',
    'selectCategory': 'வகையைத் தேர்ந்தெடுக்கவும்',
    'edit': 'திருத்தவும்',
    'delete': 'நீக்கவும்',
    'manageCrops': 'உங்கள் பயிர்களை நிர்வகிக்கவும் மற்றும் அவற்றின் முன்னேற்றத்தைக் கண்காணிக்கவும்',
    'todayTipsReminders': 'இன்றைய குறிப்புகள் மற்றும் நினைவூட்டல்கள்',
    'irrigationReminder': 'நீர்ப்பாசன நினைவூட்டல்',
    'waterRiceCrop': 'உங்கள் நெல் பயிருக்கு தண்ணீர் கொடுங்கள் - காலை 6-8 மணிக்கு இடையில் சிறந்த நேரம்',
    'pestAlert': 'பூச்சி எச்சரிக்கை',
    'brownPlanthopper': 'அருகிலுள்ள வயல்களில் பழுப்பு நிற தாவர துள்ளி காணப்பட்டது',
    'fertilizerSchedule': 'உர அட்டவணை',
    'applyUreaFertilizer': 'இன்று கோதுமை பயிருக்கு யூரியா உரம் இடுங்கள்',
    
    // Market
    'latestMandiRates': 'சமீபத்திய மண்டி விலைகள் மற்றும் பொருட்களின் விலைகள்',
    'searchCropsVarieties': 'பயிர்கள் மற்றும் வகைகளைத் தேடுங்கள்...',
    'allCrops': 'அனைத்து பயிர்கள்',
    'cereals': 'தானியங்கள்',
    'cashCrops': 'பணப்பயிர்கள்',
    'priceAlerts': 'விலை எச்சரிக்கைகள்',
    
    // Government & Schemes
    'governmentSchemes': 'அரசு திட்டங்கள்',
    'exploreApplySchemes': 'பல்வேறு அரசு திட்டங்களை ஆராய்ந்து விண்ணப்பிக்கவும்',
    'governmentProcurement': 'அரசு கொள்முதல்',
    'mspWheatAnnounced': 'கோதுமைக்கான MSP ₹2325/குவிண்டால் என அறிவிக்கப்பட்டது',
    'weatherClimate': 'வானிலை மற்றும் காலநிலை',
    
    // Additional Market & Schemes translations
    'viewDetails': 'விவரங்களைப் பார்க்கவும்',
    'marketTips': 'சந்தை குறிப்புகள்',
    'bestSellingTime': 'சிறந்த விற்பனை நேரம்',
    'riceExpectedRise': 'அரிசி விலை ஏற்றம் எதிர்பார்க்கப்படுகிறது',
    'searchSchemes': 'திட்டங்களைத் தேடுங்கள்...',
    'all': 'அனைத்து',
    'central': 'மத்திய',
    'totalSchemes': 'மொத்த திட்டங்கள்',
    'avgBenefit': 'சராசரி நன்மை',
    'beneficiaries': 'பயனாளிகள்',
    'ongoing': 'நடந்து கொண்டிருக்கும்',
    'requiredDocuments': 'தேவையான ஆவணங்கள்',
    'applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'applicationTips': 'விண்ணப்ப குறிப்புகள்',
    'documentsReady': 'அனைத்து ஆவணங்களையும் தயாராக வைத்திருங்கள்',
    'applyEarly': 'செயல்பாடு தேதிக்கு முன்பாக விண்ணப்பிக்கவும்',
    'visitCSC': 'உங்கள் அருகிலுள்ள CSC மற்றும் விவசாய அலுவலகத்தை நேரில் சென்று உதவி பெறவும்',
    'keepReceipts': 'அனைத்து ரசீதுகளையும் பாதுகாப்பாக வைத்திருங்கள்',
    'dashboardOverview': 'டாஷ்போர்டு அவலோகனம்',
    'manageYourCrops': 'உங்கள் பயிர்களை நிர்வகிக்கவும்',
    'smartFarmingCalendar': 'ஸ்மார்ட் விவசாய நாட்காட்டி',
    'getCurrentMarketRates': 'தற்போதைய சந்தை விலைகள்',
    'getExpertAdvice': 'நிபுணர் ஆலோசனை பெறவும்',
    'identifyCropDiseases': 'பயிர் நோய்களை கண்டறியவும்',
    
    // Additional crop translations
    'rice': 'அரிசி',
    'wheat': 'கோதுமை',
    'corn': 'சோளம்',
    'maize': 'சோளம்',
    'millets': 'தினை',
    'oats': 'ஓட்ஸ்',
    'soybeans': 'சோயாபீன்',
    'soybean': 'சோயாபீன்',
    'sugarcane': 'கரும்பு',
    'cotton': 'பருத்தி',
    'chickpea': 'கடலை',
    'mustard': 'கடுகு',
    'potato': 'உருளைக்கிழங்கு',
    'tomato': 'தக்காளி',
    'onion': 'வெங்காயம்',
    'other': 'மற்றவை',
    'Rice': 'அரிசி',
    'Wheat': 'கோதுமை',
    'Maize': 'சோளம்',
    'Cotton': 'பருத்தி',
    'Sugarcane': 'கரும்பு',
    'Soybean': 'சோயாபீன்',
    'Basmati': 'பாஸ்மதி',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032',
    'Kapas': 'கபாஸ்',
    'Yellow Corn': 'மஞ்சள் சோளம்',
    'JS-335': 'JS-335',
    
    // Scheme name translations
    'PM-KISAN': 'பிரதான் மந்திரி கிசான் சம்மான் நிதி',
    'Crop Insurance': 'பயிர் காப்பீடு',
    'Soil Health Card': 'மண் ஆரோக்கிய அட்டை',
    'KCC': 'கிசான் கிரெடிட் கார்டு',
    'Organic Farming': 'இயற்கை விவசாயம்',
    'Solar Pump': 'சூரிய பம்ப்',
    
    // Common
    'submit': 'சமர்ப்பிக்கவும்',
    'cancel': 'ரத்து செய்யவும்',
    'save': 'சேமிக்கவும்',
    'back': 'பின்',
    'next': 'அடுத்து',
    'welcome': 'வரவேற்கிறோம்',
    'loading': 'ஏற்றுகிறது...',
    'newToKrishiDost': 'கிருஷி தோஸ்ட்டில் புதியவரா?',
    'createNewAccount': 'புதிய கணக்கை உருவாக்கவும்',
  },
  te: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'కృషి దోస్త్ కు స్వాగతం',
    'smartCropAdvisory': 'స్మార్ట్ క్రాప్ అడ్వైజరీ',
    'krishiDost': 'కృషి దోస్త్',
    'digitalFarmingCompanion': 'మీ డిజిటల్ వ్యవసాయ సహాయి',
    'getStarted': 'ప్రారంభించండి',
    'tutorialVideo': 'ట్యుటోరియల్ వీడియో',
    'skip': 'దాటవేయండి',
    'chooseYourLanguage': 'మీ భాషను ఎంచుకోండి',
    
    // Navigation & Pages
    'dashboard': 'డాష్బోర్డ్',
    'myCrop': 'నా పంట',
    'myCrops': 'నా పంటలు',
    'aiCropCalendar': 'AI పంట క్యాలెండర్',
    'marketPrice': 'మార్కెట్ ధర',
    'marketPrices': 'మార్కెట్ ధరలు',
    'govtSchemes': 'ప్రభుత్వ పథకాలు',
    'expertHelp': 'నిపుణుల సహాయం',
    'cameraDetection': 'కెమెరా గుర్తింపు',
    'mainMenu': 'ప్రధాన మెనూ',
    'governmentSchemes': 'ప్రభుత్వ పథకాలు',
    
    // Form Fields
    'yourName': 'మీ పేరు',
    'enterFullName': 'మీ పూర్తి పేరును నమోదు చేయండి',
    'password': 'పాస్‌వర్డ్',
    'enterPassword': 'మీ పాస్‌వర్డ్ను నమోదు చేయండి',
    'confirmPassword': 'పాస్‌వర్డ్ను నిర్ధారించండి',
    'confirmYourPassword': 'మీ పాస్‌వర్డ్ను నిర్ధారించండి',
    'login': 'లాగిన్',
    'register': 'నమోదు',
    'continueOffline': 'ఆఫ్‌లైన్‌లో కొనసాగించండి',
    
    // Navigation & Basic Keys (using English as fallback for now)
    'dashboard': 'Dashboard',
    'myCrop': 'My Crop',
    'myCrops': 'My Crops',
    'aiCropCalendar': 'AI Crop Calendar',
    'marketPrice': 'Market Price',
    'marketPrices': 'Market Prices',
    'govtSchemes': 'Govt Schemes',
    'expertHelp': 'Expert Help',
    'cameraDetection': 'Camera Detection',
    'mainMenu': 'Main Menu',
    'governmentSchemes': 'Government Schemes',
    'addNewCrop': 'Add New Crop',
    'addCrop': 'Add Crop',
    'area': 'Area',
    'plantedDate': 'Planted Date',
    'applyNow': 'ఇప్పుడే దరఖాస్తు చేయండి',
    'dashboard': 'డాష్బోర్డ్',
    'myCrop': 'నా పంట',
    'myCrops': 'నా పంటలు',
    'aiCropCalendar': 'AI పంట క్యాలెండర్',
    'marketPrice': 'మార్కెట్ ధర',
    'marketPrices': 'మార్కెట్ ధరలు',
    'govtSchemes': 'ప్రభుత్వ పథకాలు',
    'expertHelp': 'నిపుణుల సహాయం',
    'cameraDetection': 'కెమెరా గుర్తింపు',
    'mainMenu': 'ప్రధాన మెనూ',
    'goodMorningFarmer': 'శుభోదయం, రైతు గారు!',
    'weather': 'వాతావరణం',
    'alerts': 'హెచ్చరికలు',
    'open': 'తెరవండి',
    'farmingDashboardToday': 'ఇన్ని మీ వ్యవసాయ డాష్బోర్డ్',
    'checkCropsField': 'వయల్లో మీ పంటలను చూడండి',
    'todayMandiRates': 'ఇన్ని మండీ రేటులు',
    'availableGovtSchemes': 'లభ్యమైన ప్రభుత్వ పథకాలు',
    'connectExperts': 'వ్యవసాయ నిపుణులతో కలుపుకోండి',
    'rainfall': 'వర్షం',
    'season': 'ఋతువు',
    'newAlerts': 'కొత్త హెచ్చరికలు',
    'voiceAssistant': 'వాయిస్ అసిస్టెంట్',
    'askFarmingQuestions': 'ఏదైనా వ్యవసాయ ప్రశ్నలను నన్ను అడగండి',
    'startVoiceChat': 'వాయిస్ చాట్ ప్రారంభించండి',
    'recentActivity': 'ఇక్కడ కార్యకలాపాలు',
    'riceCropUpdated': 'వాదలు పంట స్థితి అప్డేట్ అయ్యింది',
    'hoursAgo': 'గంటల క్రితం',
    'marketPriceAlert': 'మార్కెట్ విలువ హెచ్చరిక వచ్చింది',
    'latestMandiRates': 'తాజా మండీ రేటులు మరియు వస్తువుల విలువలు',
    'searchCropsVarieties': 'పంటలు మరియు విధాలను వెతకండి...',
    'allCrops': 'అన్ని పంటలు',
    'cereals': 'ధాన్యాలు',
    'cashCrops': 'పణపు పంటలు',
    'priceAlerts': 'విలువ హెచ్చరికలు',
    'exploreApplySchemes': 'వివిధ ప్రభుత్వ పథకాలను అన్వేషించి దరఖాస్తు చేయండి',
    'governmentProcurement': 'ప్రభుత్వ కొలుగోలు',
    'mspWheatAnnounced': 'గోధుమలకు MSP ₹2325/క్వింటల్ గా ప్రకటించబడింది',
    'weatherClimate': 'వాతావరణం మరియు వాతావరణ మార్పు',
    'dashboardOverview': 'డాష్బోర్డ్ అవలోకనం',
    'manageYourCrops': 'మీ పంటలను నిర్వహించండి',
    'smartFarmingCalendar': 'స్మార్ట్ వ్యవసాయ క్యాలెండర్',
    'getCurrentMarketRates': 'ప్రస్తుత మార్కెట్ రేటులు',
    'getExpertAdvice': 'నిపుణుల సలహా తీసుకోండి',
    'identifyCropDiseases': 'పంట రోగాలను గుర్తించండి',
    
    // Additional crop translations
    'rice': 'వాదలు',
    'wheat': 'గోధుమలు',
    'corn': 'మక్కజోళం',
    'maize': 'మక్కజోళం',
    'millets': 'సజ్జలు',
    'oats': 'వోట్స్',
    'soybeans': 'సోయాబీన్',
    'soybean': 'సోయాబీన్',
    'sugarcane': 'కల్లపండు',
    'cotton': 'పట్టి',
    'chickpea': 'శనగలు',
    'mustard': 'ఆవాలు',
    'potato': 'బంగాళాదుంప',
    'tomato': 'టమోటా',
    'onion': 'ఉల్లిపాయ',
    'other': 'ఇతర',
    'Rice': 'వాదలు',
    'Wheat': 'గోధుమలు',
    'Maize': 'మక్కజోళం',
    'Cotton': 'పట్టి',
    'Sugarcane': 'కల్లపండు',
    'Soybean': 'సోయాబీన్',
    'Basmati': 'బాస్మతీ',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032',
    'Kapas': 'కపాస్',
    'Yellow Corn': 'మంజు మక్కజోళం',
    'JS-335': 'JS-335',
    
    // Scheme name translations
    'PM-KISAN': 'ప్రధానమంత్రి కిసాన్ సమ్మాన్ నిధి',
    'Crop Insurance': 'పంట వీమ',
    'Soil Health Card': 'మృత్తిక ఆరోగ్య కార్డు',
    'KCC': 'కిసాన్ క్రెడిట్ కార్డు',
    'Organic Farming': 'సేంద్రియ వ్యవసాయం',
    'Solar Pump': 'సౌర పంపు',
    
    // Common
    'submit': 'సబ్మిట్ చేయండి',
    'cancel': 'రద్దు చేయండి',
    'save': 'సేవ్ చేయండి',
    'back': 'వెనుకకు',
    'next': 'తదుపరి',
    'welcome': 'స్వాగతం',
    'loading': 'లోడ్ అవుతోంది...',
    'newToKrishiDost': 'కృషి దోస్త్‌కు కొత్తవారా?',
    'createNewAccount': 'కొత్త ఖాతా సృష్టించండి',
  },
  pa: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'ਕ੍ਰਿਸ਼ੀ ਦੋਸਤ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    'smartCropAdvisory': 'ਸਮਾਰਟ ਫਸਲ ਸਲਾਹਕਾਰ',
    'krishiDost': 'ਕ੍ਰਿਸ਼ੀ ਦੋਸਤ',
    'digitalFarmingCompanion': 'ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਖੇਤੀ ਸਾਥੀ',
    'getStarted': 'ਸ਼ੁਰੂ ਕਰੋ',
    'tutorialVideo': 'ਟਿਊਟੋਰੀਅਲ ਵੀਡੀਓ',
    'skip': 'ਛੱਡੋ',
    'chooseYourLanguage': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    
    // Form Fields
    'yourName': 'ਤੁਹਾਡਾ ਨਾਮ',
    'enterFullName': 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    'password': 'ਪਾਸਵਰਡ',
    'enterPassword': 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    'confirmPassword': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'confirmYourPassword': 'ਆਪਣੇ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'login': 'ਲਾਗਇਨ',
    'register': 'ਰਜਿਸਟਰ',
    'continueOffline': 'ਆਫਲਾਈਨ ਜਾਰੀ ਰੱਖੋ',
    
    // Navigation & Basic Keys (using English as fallback for now)
    'dashboard': 'Dashboard',
    'myCrop': 'My Crop',
    'myCrops': 'My Crops',
    'aiCropCalendar': 'AI Crop Calendar',
    'marketPrice': 'Market Price',
    'marketPrices': 'Market Prices',
    'govtSchemes': 'Govt Schemes',
    'expertHelp': 'Expert Help',
    'cameraDetection': 'Camera Detection',
    'mainMenu': 'Main Menu',
    'governmentSchemes': 'Government Schemes',
    'addNewCrop': 'Add New Crop',
    'addCrop': 'Add Crop',
    'area': 'Area',
    'plantedDate': 'Planted Date',
    'applyNow': 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
    'goodMorningFarmer': 'ਸਤਿ ਅਕਾਲ, ਕਿਸਾਨ ਜੀ!',
    'weather': 'ਮੌਸਮ',
    'alerts': 'ਅਲਰਟ',
    'open': 'ਖੋਲ੍ਹੋ',
    'farmingDashboardToday': 'ਅੱਜ ਦੇ ਲਈ ਤੁਹਾਡਾ ਖੇਤੀ ਡੈਸ਼ਬੋਰਡ',
    'checkCropsField': 'ਖੇਤ ਵਿੱਚ ਆਪਣੀਆਂ ਫਸਲਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    'todayMandiRates': 'ਅੱਜ ਦੇ ਮੰਡੀ ਰੇਟ',
    'availableGovtSchemes': 'ਉਪਲਬਧ ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    'connectExperts': 'ਖੇਤੀ ਮਾਹਰਾਂ ਨਾਲ ਜੁੜੋ',
    'rainfall': 'ਮੀਂਹ',
    'season': 'ਮੌਸਮ',
    'newAlerts': 'ਨਵੇਂ ਅਲਰਟ',
    'voiceAssistant': 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    'askFarmingQuestions': 'ਮੇਰੇ ਤੋਂ ਕੋਈ ਵੀ ਖੇਤੀ ਸਵਾਲ ਪੁੱਛੋ',
    'startVoiceChat': 'ਆਵਾਜ਼ ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ',
    'recentActivity': 'ਹਾਲ ਦੀ ਗਤੀਵਿਧੀ',
    'riceCropUpdated': 'ਚਾਵਲ ਦੀ ਫਸਲ ਦੀ ਸ੍ਥਿਤੀ ਅਪਡੇਟ ਹੋਈ',
    'hoursAgo': 'ਘੰਟੇ ਪਹਿਲਾਂ',
    'marketPriceAlert': 'ਮਾਰਕੀਟ ਰੇਟ ਅਲਰਟ ਮਿਲਿਆ',
    'latestMandiRates': 'ਤਾਜ਼ਾ ਮੰਡੀ ਰੇਟ ਅਤੇ ਵਸਤੂਆਂ ਦੇ ਭਾਅ',
    'searchCropsVarieties': 'ਫਸਲਾਂ ਅਤੇ ਕਿਸਮਾਂ ਦੀ ਖੋਜ ਕਰੋ...',
    'allCrops': 'ਸਾਰੀਆਂ ਫਸਲਾਂ',
    'cereals': 'ਅਨਾਜ',
    'cashCrops': 'ਨਕਦੀ ਫਸਲਾਂ',
    'priceAlerts': 'ਰੇਟ ਅਲਰਟ',
    'exploreApplySchemes': 'ਵੱਖ-ਵੱਖ ਸਰਕਾਰੀ ਸਕੀਮਾਂ ਦੀ ਖੋਜ ਕਰੋ ਅਤੇ ਅਰਜ਼ੀ ਦਿਓ',
    'governmentProcurement': 'ਸਰਕਾਰੀ ਖਰੀਦ',
    'mspWheatAnnounced': 'ਕਣਕ ਲਈ MSP ₹2325/ਕੁਿੰਟਲ ਦੀ ਘੋਸ਼ਣਾ',
    'weatherClimate': 'ਮੌਸਮ ਅਤੇ ਜਲਵਾਯੂ',
    'dashboardOverview': 'ਡੈਸ਼ਬੋਰਡ ਅਵਲੋਕਨ',
    'manageYourCrops': 'ਆਪਣੀਆਂ ਫਸਲਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
    'smartFarmingCalendar': 'ਸਮਾਰਟ ਖੇਤੀ ਕੈਲੰਡਰ',
    'getCurrentMarketRates': 'ਵਰਤਮਾਨ ਮਾਰਕੀਟ ਰੇਟ',
    'getExpertAdvice': 'ਮਾਹਰ ਸਲਾਹ ਲੈਣ ਦਿਓ',
    'identifyCropDiseases': 'ਫਸਲ ਰੋਗਾਂ ਦੀ ਪਹਿਚਾਣ ਕਰੋ',
    
    // Additional crop translations
    'rice': 'ਚਾਵਲ',
    'wheat': 'ਕਣਕ',
    'corn': 'ਮਕੈ',
    'maize': 'ਮਕੈ',
    'millets': 'ਬਾਜਰਾ',
    'oats': 'ਜਈ',
    'soybeans': 'ਸੋਯਾਬੀਨ',
    'soybean': 'ਸੋਯਾਬੀਨ',
    'sugarcane': 'ਗਨ੍ਨਾ',
    'cotton': 'ਕਪਾਹ',
    'chickpea': 'ਚਨਾ',
    'mustard': 'ਸਰ੍ਹੋਂ',
    'potato': 'ਆਲੂ',
    'tomato': 'ਟਮਾਟਰ',
    'onion': 'ਪਿਆਜ਼',
    'other': 'ਹੋਰ',
    'Rice': 'ਚਾਵਲ',
    'Wheat': 'ਕਣਕ',
    'Maize': 'ਮਕੈ',
    'Cotton': 'ਕਪਾਹ',
    'Sugarcane': 'ਗਨ੍ਨਾ',
    'Soybean': 'ਸੋਯਾਬੀਨ',
    'Basmati': 'ਬਾਸਮਤੀ',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032',
    'Kapas': 'ਕਪਾਸ',
    'Yellow Corn': 'ਪੀਲੀ ਮਕੈ',
    'JS-335': 'JS-335',
    
    // Scheme name translations
    'PM-KISAN': 'ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਕਿਸਾਨ ਸਮਾਨ ਨਿਧੀ',
    'Crop Insurance': 'ਫਸਲ ਬੀਮਾ',
    'Soil Health Card': 'ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ',
    'KCC': 'ਕਿਸਾਨ ਕ੍ਰੈਡਿਟ ਕਾਰਡ',
    'Organic Farming': 'ਜੈਵਿਕ ਖੇਤੀ',
    'Solar Pump': 'ਸੌਰ ਪੰਪ',
    
    // Common
    'submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
    'cancel': 'ਰੱਦ ਕਰੋ',
    'save': 'ਸੇਵ ਕਰੋ',
    'back': 'ਵਾਪਸ',
    'next': 'ਅਗਲਾ',
    'welcome': 'ਸਵਾਗਤ',
    'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'newToKrishiDost': 'ਕ੍ਰਿਸ਼ੀ ਦੋਸਤ ਵਿੱਚ ਨਵੇਂ ਹੋ?',
    'createNewAccount': 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
  },
  ur: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'کرشی دوست میں آپ کا خوش آمدید',
    'smartCropAdvisory': 'سمارٹ کراپ ایڈوائزری',
    'krishiDost': 'کرشی دوست',
    'digitalFarmingCompanion': 'آپ کا ڈیجیٹل کاشتکاری ساتھی',
    'getStarted': 'شروع کریں',
    'tutorialVideo': 'ٹیوٹوریل ویڈیو',
    'skip': 'چھوڑیں',
    'chooseYourLanguage': 'اپنی زبان منتخب کریں',
    
    // Form Fields
    'yourName': 'آپ کا نام',
    'enterFullName': 'اپنا پورا نام درج کریں',
    'password': 'پاس ورڈ',
    'enterPassword': 'اپنا پاس ورڈ درج کریں',
    'confirmPassword': 'پاس ورڈ کی تصدیق کریں',
    'confirmYourPassword': 'اپنے پاس ورڈ کی تصدیق کریں',
    'login': 'لاگ ان',
    'register': 'رجسٹر',
    'continueOffline': 'آف لائن جاری رکھیں',
    
    // Navigation & Basic Keys (using English as fallback for now)
    'dashboard': 'Dashboard',
    'myCrop': 'My Crop',
    'myCrops': 'My Crops',
    'aiCropCalendar': 'AI Crop Calendar',
    'marketPrice': 'Market Price',
    'marketPrices': 'Market Prices',
    'govtSchemes': 'Govt Schemes',
    'expertHelp': 'Expert Help',
    'cameraDetection': 'Camera Detection',
    'mainMenu': 'Main Menu',
    'governmentSchemes': 'Government Schemes',
    'addNewCrop': 'Add New Crop',
    'addCrop': 'Add Crop',
    'area': 'Area',
    'plantedDate': 'Planted Date',
    'applyNow': 'اب اپلائی کریں',
    'goodMorningFarmer': 'صبح بخیر، کسان!',
    'weather': 'موسم',
    'alerts': 'الرٹ',
    'open': 'کھولیں',
    'farmingDashboardToday': 'آج کے لیے آپ کا زراعتی ڈیش بورڈ',
    'checkCropsField': 'کھیت میں اپنی فصلوں کی جانچ کریں',
    'todayMandiRates': 'آج کے منڈی ریٹ',
    'availableGovtSchemes': 'دستیاب حکومتی اسکیمیں',
    'connectExperts': 'زراعتی ماہرین سے رابطہ',
    'rainfall': 'بارش',
    'season': 'موسم',
    'newAlerts': 'نئے الرٹ',
    'voiceAssistant': 'آوازی مددگار',
    'askFarmingQuestions': 'مجھ سے کوئی بھی زراعتی سوال پوچھیں',
    'startVoiceChat': 'آوازی بات شروع کریں',
    'recentActivity': 'حالیہ سرگرمی',
    'riceCropUpdated': 'چاول کی فصل کی صورتحال اپ ڈیٹ ہوئی',
    'hoursAgo': 'گھنٹے پہلے',
    'marketPriceAlert': 'مارکیٹ ریٹ الرٹ ملا',
    'latestMandiRates': 'تازہ منڈی ریٹ اور اجناس کی قیمتیں',
    'searchCropsVarieties': 'فصلوں اور قسموں کی تلاش کریں...',
    'allCrops': 'تمام فصلیں',
    'cereals': 'اناج',
    'cashCrops': 'نقدی فصلیں',
    'priceAlerts': 'قیمت الرٹ',
    'exploreApplySchemes': 'مختلف حکومتی اسکیموں کی تلاش اور اپلائی کریں',
    'governmentProcurement': 'حکومتی خریداری',
    'mspWheatAnnounced': 'گیہوں کے لیے MSP ₹2325/کونٹل کا اعلان',
    'weatherClimate': 'موسم اور آب و ہوا',
    'dashboardOverview': 'ڈیش بورڈ جائزہ',
    'manageYourCrops': 'اپنی فصلوں کا انتظام کریں',
    'smartFarmingCalendar': 'سمارٹ زراعتی کیلنڈر',
    'getCurrentMarketRates': 'موجودہ مارکیٹ ریٹ',
    'getExpertAdvice': 'ماہر مشورہ حاصل کریں',
    'identifyCropDiseases': 'فصلی بیماریوں کی شناخت کریں',
    
    // Additional crop translations
    'rice': 'چاول',
    'wheat': 'گیہوں',
    'corn': 'مکئی',
    'maize': 'مکئی',
    'millets': 'باجرہ',
    'oats': 'جئی',
    'soybeans': 'سویا بین',
    'soybean': 'سویا بین',
    'sugarcane': 'گنا',
    'cotton': 'کپاس',
    'chickpea': 'چنا',
    'mustard': 'سرسوں',
    'potato': 'آلو',
    'tomato': 'ٹماٹر',
    'onion': 'پیاز',
    'other': 'دیگر',
    'Rice': 'چاول',
    'Wheat': 'گیہوں',
    'Maize': 'مکئی',
    'Cotton': 'کپاس',
    'Sugarcane': 'گنا',
    'Soybean': 'سویا بین',
    'Basmati': 'باسمتی',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032',
    'Kapas': 'کپاس',
    'Yellow Corn': 'پیلی مکئی',
    'JS-335': 'JS-335',
    
    // Scheme name translations
    'PM-KISAN': 'وزیر اعظم کسان سمان ندھی',
    'Crop Insurance': 'فصلی بیمہ',
    'Soil Health Card': 'مٹی کی صحت کارڈ',
    'KCC': 'کسان کریڈٹ کارڈ',
    'Organic Farming': 'نیچرل کھیتی',
    'Solar Pump': 'شمسی پمپ',
    
    // Common
    'submit': 'جمع کریں',
    'cancel': 'منسوخ',
    'save': 'محفوظ کریں',
    'back': 'واپس',
    'next': 'اگلا',
    'welcome': 'خوش آمدید',
    'loading': 'لوڈ ہو رہا ہے...',
    'newToKrishiDost': 'کرشی دوست میں نئے ہیں؟',
    'createNewAccount': 'نیا اکاؤنٹ بنائیں',
  },
  ml: {
    // App Title & Welcome
    'welcomeToKrishiDost': 'കൃഷി ദോസ്തിലേക്ക് സ്വാഗതം',
    'smartCropAdvisory': 'സ്മാർട്ട് ക്രോപ്പ് അഡ്വൈസറി',
    'krishiDost': 'കൃഷി ദോസ്ത്',
    'digitalFarmingCompanion': 'നിങ്ങളുടെ ഡിജിറ്റൽ കൃഷി സഹായി',
    'getStarted': 'ആരംഭിക്കുക',
    'tutorialVideo': 'ട്യൂട്ടോറിയൽ വീഡിയോ',
    'skip': 'ഒഴിവാക്കുക',
    'chooseYourLanguage': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    
    // Form Fields
    'yourName': 'നിങ്ങളുടെ പേര്',
    'enterFullName': 'നിങ്ങളുടെ പൂർണ്ണ നാമം നൽകുക',
    'password': 'പാസ്‌വേഡ്',
    'enterPassword': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
    'confirmPassword': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'confirmYourPassword': 'നിങ്ങളുടെ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'login': 'ലോഗിൻ',
    'register': 'രജിസ്റ്റർ',
    'continueOffline': 'ഓഫ്‌ലൈനായി തുടരുക',
    
    // Navigation & Basic Keys (using English as fallback for now)
    'dashboard': 'Dashboard',
    'myCrop': 'My Crop',
    'myCrops': 'My Crops',
    'aiCropCalendar': 'AI Crop Calendar',
    'marketPrice': 'Market Price',
    'marketPrices': 'Market Prices',
    'govtSchemes': 'Govt Schemes',
    'expertHelp': 'Expert Help',
    'cameraDetection': 'Camera Detection',
    'mainMenu': 'Main Menu',
    'governmentSchemes': 'Government Schemes',
    'addNewCrop': 'Add New Crop',
    'addCrop': 'Add Crop',
    'area': 'Area',
    'plantedDate': 'Planted Date',
    'applyNow': 'ഇപ്പോൾ അപ്ലൈ ചെയ്യുക',
    'goodMorningFarmer': 'സുപ്രഭാതം, കൃഷിക്കാരൻ!',
    'weather': 'കാലാവസ്ഥ',
    'alerts': 'അലർട്ടുകൾ',
    'open': 'തുറക്കുക',
    'farmingDashboardToday': 'ഇന്നത്തെ നിങ്ങളുടെ കൃഷി ഡാഷ്ബോർഡ്',
    'checkCropsField': 'വയലിലെ നിങ്ങളുടെ വിളകള്‍ പരിശോധിക്കുക',
    'todayMandiRates': 'ഇന്നത്തെ മണ്ഡി വിലകള്‍',
    'availableGovtSchemes': 'ലഭ്യമായ സർക്കാർ പദ്ധതികള്‍',
    'connectExperts': 'കൃഷി വിശേഷഞ്ഞരുമായി യോഗം ചെയ്യുക',
    'rainfall': 'മഴപ്പൊഴിവ്',
    'season': 'കാലം',
    'newAlerts': 'പുതിയ അലർട്ടുകള്‍',
    'voiceAssistant': 'വോയ്സ് അസിസ്റ്റന്റ്',
    'askFarmingQuestions': 'എന്നോട് ഏതെങ്കിലും കൃഷി ചോദ്യങ്ങള്‍ ചോദിക്കുക',
    'startVoiceChat': 'വോയ്സ് ചാറ്റ് ആരംഭിക്കുക',
    'recentActivity': 'ഇതിന്റെ പ്രവർത്തനങ്ങള്‍',
    'riceCropUpdated': 'നെല്ലിന്റെ സ്ഥിതി അപ്ഡേറ്റ് ചെയ്തു',
    'hoursAgo': 'മണിക്കൂർ മുമ്പ്',
    'marketPriceAlert': 'മാർക്കറ്റ് വില അലർട്ട് ലഭിച്ചു',
    'latestMandiRates': 'ഏറ്റവും പുതിയ മണ്ഡി വിലകളും വസ്തുക്കളുടെ വിലകളും',
    'searchCropsVarieties': 'വിളകളും വരീയറ്റികളും തെടുക്കുക...',
    'allCrops': 'എല്ലാ വിളകളും',
    'cereals': 'ധാന്യങ്ങള്',
    'cashCrops': 'പണവിളകള്',
    'priceAlerts': 'വില അലർട്ടുകള്',
    'exploreApplySchemes': 'വിവിധ സർക്കാർ പദ്ധതികള് അന്വേഷിച്ച് അപ്ലിക്കേഷന് നൽകുക',
    'governmentProcurement': 'സർക്കാർ കൊള്ളല്',
    'mspWheatAnnounced': 'ഗോധുമയ്ക്ക് MSP ₹2325/ക്വിന്റല് എന്ന് അറിയിച്ചു',
    'weatherClimate': 'കാലാവസ്ഥയും കാലാവസ്ഥാ മാറ്റവും',
    'dashboardOverview': 'ഡാഷ്ബോർഡ് അവലോകനം',
    'manageYourCrops': 'നിങ്ങളുടെ വിളകള് നിര്വഹിക്കുക',
    'smartFarmingCalendar': 'സ്മാർട്ട് കൃഷി ക്യാലണ്ടർ',
    'getCurrentMarketRates': 'നിലവിലെ മാർക്കറ്റ് രേറ്റുകള്',
    'getExpertAdvice': 'വിശേഷഞ്ഞ ഉപദേശം നേടുക',
    'identifyCropDiseases': 'വിള രോഗങ്ങള് കണ്ടെത്തുക',
    
    // Additional crop translations
    'rice': 'അരി',
    'wheat': 'ഗോധുമയ്',
    'corn': 'ചോളം',
    'maize': 'ചോളം',
    'millets': 'തിനകള്',
    'oats': 'ഓട്സ്',
    'soybeans': 'സോയാബീൻ',
    'soybean': 'സോയാബീൻ',
    'sugarcane': 'കരിംപ്',
    'cotton': 'പരുത്തി',
    'chickpea': 'കടല',
    'mustard': 'കടുക്',
    'potato': 'ഉരുളക്കിഴങ്ങ്',
    'tomato': 'തക്കാളി',
    'onion': 'ഉള്ളി',
    'other': 'മറ്റുള്ളവ',
    'Rice': 'അരി',
    'Wheat': 'ഗോധുമയ്',
    'Maize': 'ചോളം',
    'Cotton': 'പരുത്തി',
    'Sugarcane': 'കരിംപ്',
    'Soybean': 'സോയാബീൻ',
    'Basmati': 'ബാസ്മതി',
    'HD-2967': 'HD-2967',
    'Co-86032': 'Co-86032',
    'Kapas': 'കപാസ്',
    'Yellow Corn': 'മഞ്ഞ ചോളം',
    'JS-335': 'JS-335',
    
    // Scheme name translations
    'PM-KISAN': 'പ്രധാനമന്ത്രി കിസാൻ സമ്മാൻ നിധി',
    'Crop Insurance': 'വിള ഇൻഷ്വറൻസ്',
    'Soil Health Card': 'മണ്ണിന്റെ ആരോഗ്യ കാർഡ്',
    'KCC': 'കിസാൻ ക്രെഡിറ്റ് കാർഡ്',
    'Organic Farming': 'ഓർഗാനിക് കൃഷി',
    'Solar Pump': 'സൌര പമ്പ്',
    
    // Common
    'submit': 'സമർപ്പിക്കുക',
    'cancel': 'റദ്ദാക്കുക',
    'save': 'സേവ് ചെയ്യുക',
    'back': 'തിരികെ',
    'next': 'അടുത്തത്',
    'welcome': 'സ്വാഗതം',
    'loading': 'ലോഡ് ചെയ്യുന്നു...',
    'newToKrishiDost': 'കൃഷി ദോസ്തിൽ പുതിയവരാണോ?',
    'createNewAccount': 'പുതിയ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
  }
};