// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhopqgygehzmohlumrum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impob3BxZ3lnZWh6bW9obHVtcnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODE4NjAsImV4cCI6MjA3MzE1Nzg2MH0.KlnKhJaPdntzrL28aizeWCwHWvbVPGguCC3wuSo51IY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});